In [1]:
import torch
import torch.nn as nn
import numpy as np

In [23]:
torch.manual_seed(0)
input_size = 1
hidden_size = 5
num_layers = 1
rnn = nn.RNN(input_size,hidden_size,num_layers,bias=False)
rnn._parameters

OrderedDict([('weight_ih_l0', Parameter containing:
              tensor([[-0.0033],
                      [ 0.2399],
                      [-0.3681],
                      [-0.3291],
                      [-0.1722]], requires_grad=True)),
             ('weight_hh_l0', Parameter containing:
              tensor([[ 0.1199, -0.0089,  0.3546, -0.0397,  0.1183],
                      [-0.1352, -0.0879, -0.4272, -0.2962, -0.1844],
                      [ 0.0166,  0.1768,  0.2683, -0.3032, -0.1947],
                      [ 0.1624,  0.3714, -0.0920,  0.3347, -0.0721],
                      [ 0.0473,  0.4049, -0.4149, -0.2815, -0.1132]], requires_grad=True))])

In [44]:
W_ih = torch.tensor([[-0.0033],
                     [ 0.2399],
                     [-0.3681],
                     [-0.3291],
                     [-0.1722]])
W_hh = torch.tensor([[ 0.1199, -0.0089,  0.3546, -0.0397,  0.1183],
                     [-0.1352, -0.0879, -0.4272, -0.2962, -0.1844],
                     [ 0.0166,  0.1768,  0.2683, -0.3032, -0.1947],
                     [ 0.1624,  0.3714, -0.0920,  0.3347, -0.0721],
                     [ 0.0473,  0.4049, -0.4149, -0.2815, -0.1132]])
x = torch.tensor([[[1.]]])
hidden = torch.tensor([[1.,0.,0.,0.,0.]]).view(1,1,-1)
print(W_ih + torch.matmul(W_hh,torch.tensor([[1.,0.,0.,0.,0.]]).T))
out, h = rnn(x,hidden)
print(out, h)

tensor([[ 0.1166],
        [ 0.1047],
        [-0.3515],
        [-0.1667],
        [-0.1249]])
tensor([[[ 0.1161,  0.1044, -0.3377, -0.1652, -0.1243]]],
       grad_fn=<StackBackward>) tensor([[[ 0.1161,  0.1044, -0.3377, -0.1652, -0.1243]]],
       grad_fn=<StackBackward>)
