In [1]:
import sys, os
sys.path.append(os.path.join(sys.path[0].split('BecaNLP')[0],'BecaNLP/Utils'))

import NLPUtils as nlp
from NLPUtils.datasets import imdb

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

%load_ext autoreload
%autoreload 2

In [3]:
from NLPUtils.datasets.utils import NgramTextVectorizer

train_corpus = imdb.train_reader()
indices = nlp.datasets.utils.split_dev_kfolds(len(train_corpus),dev_size=.2,random_state=1273)
train_idx, dev_idx = indices[0]
dev_corpus, train_corpus = train_corpus.iloc[dev_idx[:2],:], train_corpus.iloc[train_idx[:3],:]

for text in train_corpus['comment']:
    print(text)
    print()

I tried to watch this movie in a military camp during an overseas mission, and let me tell you, you'll watch anything under those circumstances. Not this piece of sh*t though.<br /><br />The first five minutes set the tone by weak porn-movie quality acting, weird out-of-the-blue plot twists and unbelievable situations and behavior. It gets worse after that. This movie does not have one single saving grace, and yet it is not bad in a way that would make it funny to watch. It's just horrible. I've seen quite many movies in my life and I'm not one of those snobby know-all critics, I mean I'll enjoy most movies to some extent even if they're bad. This one... man.<br /><br />Steer _well_ clear of this one, my friend.
I saw this film opening weekend in Australia, anticipating with an excellent cast of Ledger, Edgerton, Bloom, Watts and Rush that the definitive story of Ned Kelly would unfold before me. Unfortunately, despite an outstanding performance by Heath Ledger in the lead role, the pl

In [7]:
import time

vocabulary = None#imdb.vocab_file_reader()
unk_token = 'UNK'
ngram_range = (1,1)
token_pattern = r'\b\w+\b'
min_freq, max_freq = 0, np.inf

vectorizer = NgramTextVectorizer(vocabulary=vocabulary,ngram_range=ngram_range,
                min_freq=min_freq,max_freq=max_freq,unk_token=unk_token)

vectorizer.fit(train_corpus['comment'])

X_train = vectorizer.transform(train_corpus['comment'])
X_dev = vectorizer.transform(dev_corpus['comment'])

4.76837158203125e-06
4.0531158447265625e-05
0.0035991668701171875
0.0012743473052978516
0.0009412765502929688


Tengo dos casos posibles:
* Tengo un vocabulario abierto, en el que lo único que hago es contar las palabras que aparecieron y me quedo con todas ellas. 

* Tengo un vocabulario cerrado. Esto se puede dar por varias razones:

    * Le doy un vocabulario explícito
    * Le doy una frecuencia máxima y/o mínima de ocurrencia
    * Le doy un máximo de palabras que pueden aparecer en el vocabulario (las más frecuentes).
    
    En todos estos casos, me quedo con las palabras que integran el vocabulario y el resto, las ignoro o las trato como UNKs, dependiendo del valor de unk_token

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

corpus_train = ['Esto es una prueba',
               'esto también',
               'esto es otra prueba']

corpus_dev = ['esto es una prueba para dev',
             'esto también.',
             'esto no importa pero igual']

vocabulary = ['esto','igual','es','una']

vec = CountVectorizer(vocabulary=vocabulary,token_pattern=r'\b\w+\b',lowercase=False)
vec.fit(corpus_train)
print(vec.vocabulary_)
X = vec.transform(corpus_dev)
X.toarray()

{'esto': 0, 'igual': 1, 'es': 2, 'una': 3}


array([[1, 0, 1, 1],
       [1, 0, 0, 0],
       [1, 1, 0, 0]])

In [86]:
from NLPUtils.datasets.utils import NgramTextVectorizer

train_corpus = ['Esto es una prueba',
               'esto también',
               'esto es otra prueba']

dev_corpus = ['esto es una prueba para dev',
             'esto también.',
             'esto no importa pero igual']


# train_corpus = imdb.train_reader()
# indices = nlp.datasets.utils.split_dev_kfolds(len(train_corpus),dev_size=.2,random_state=1273)
# train_idx, dev_idx = indices[0]
# dev_corpus, train_corpus = train_corpus.iloc[dev_idx,:], train_corpus.iloc[train_idx,:]

vocabulary = None#imdb.vocab_file_reader()[:10] #['esto', 'es', 'una', 'para', 'igual']
unk_token = 'UNK'
ngram_range = (1,3)
token_pattern = r'\b\w+\b'
min_freq, max_freq = 0, 1
max_features = 10
vectorizer = NgramTextVectorizer(vocabulary=vocabulary,ngram_range=ngram_range,
                min_freq=min_freq,max_freq=max_freq,unk_token=unk_token,max_features=max_features)
X_train = vectorizer.fit_transform(train_corpus)
X_dev = vectorizer.transform(dev_corpus)

print(vectorizer.vocabulary_)
print(X_train.shape)
print(X_dev.shape)
print(X_train.toarray())
print(X_dev.toarray())

{'una prueba': 0, 'una': 1, 'también': 2, 'otra prueba': 3, 'otra': 4, 'esto también': 5, 'esto es otra': 6, 'esto es': 7, 'es una prueba': 8, 'es una': 9, 'UNK': 10}
(3, 11)
(3, 11)
[[1 1 0 0 0 0 0 0 1 1 5]
 [0 0 1 0 0 1 0 0 0 0 1]
 [0 0 0 1 1 0 1 1 0 0 5]]
[[ 1  1  0  0  0  0  0  1  1  1 10]
 [ 0  0  1  0  0  1  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0 12]]


In [61]:
train_corpus

comment  rate
5192   I tried to watch this movie in a military camp...     1
10582  I saw this film opening weekend in Australia, ...     4
14511  St. Elmo's Fire has no bearing on life after u...     1
21452  Bette Davis brings her full trunk of tics to t...     1
11081  I'd heard about this movie a while ago from a ...     3
17787  I really can't remember who recommended this, ...     8
14935  According to IMDb, as well as to every other w...     4
23827  This movie does a great job of explaining the ...    10
24267  When I first saw the Romeo Division last sprin...    10
10051  This movie could be used in film classes in a ...     2
13231  I ordered the movie from Korea because I was a...     1
23344  Having searched for this movie high and low, I...     3
1887   I watched Phat Beach on cable for a while and ...     3
24563  I caught the last half of this movie on cable ...     7
24227  This clunker of a film sets a new standard for...     1
15238  This is one of the worst horror movies I have ...     1
21530  I have been eagerly anticipating the opening o...    10
15373  I'm sorry, but this may have been scary in 197...     1
16503  I saw that movie few days ago. This movie is s...    10
22256  Not only was this the most expensive Canadian ...     1
6575   I watched 3/4 of this movie and wondered why i...     4
13850  One of the better Vance films succeeds more on...     7
10212  Garson Kanin wrote and directed this look at "...     4
14810  Reviewed at the Sept 12, 2006 2nd screening at...     7
22263  Lame, cliched superhero action movie drivel. I...     3
6689   Flat characters that you do not and never will...     3
942    and a 30,000$ budget and this movie still look...     2
21010  Super-slick entertainment with a stellar cast,...     8
23675  Geez, another Lifetime movie, but once again i...     4
10498  This film has good characters with excellent p...     7
...                                                  ...   ...
20948  I am wanting to make a "Holmes with Doors" pun...     3
1627   I don't know what that other guy was thinking....     2
22136  A trooper is on the side of the road making su...     1
7554   I have to congratulate the genius who approved...     1
2024   I am appalled at how bad this film is. As a pa...     1
5394   Steven Vasquez directed and co-wrote with Jame...     3
3698   C'mon guys some previous reviewers have nearly...     3
3179   There is a key aspect of film that Jobson seem...     2
19090  I watched this film sort of by accident, havin...    10
8144   Please make me forget. Please. Please. This is...     1
12441  This film is really terrible. terrible as in i...     1
3045   Utterly brilliant. Powerful and evocative. The...    10
17372  my friend bought the movie for 5€ (its is not ...     1
3211   Plot is never the strong point of a Fred Astai...     7
11720  this film has it all; the deft camera work, re...     1
7725   Following a roughly 7 year rocky road on NBC, ...    10
16627  I sincerely consider this movie as another poo...     3
12062  I must admit I do not hold much of New Age mum...     1
21708  There is only one problem with this website, y...     1
20814  This movie was a fantastic comedy. It had a lo...     7
2404   I'm not usually one to slate a film . I try to...     3
17131  This movie is so bad, you almost feel contamin...     1
2054   Tasteless. I can't even write intelligently ab...     1
19683  Recently, I had opportunity to view a working ...     1
15766  This is one of the better comedies that has ev...    10
9513   I know the film snobs are snorting. But if you...     8
23602  I've given up trying to figure out what versio...     3
20119  This is the best movie I`ve ever seen !!! Thom...    10
22951  Return of the Boogyman is a dreadful movie whi...     1
5536   As a lover of the surreal (in art and film) I ...     8

[20000 rows x 2 columns]