In [1]:
import sys, os
sys.path.append(os.path.join(os.getcwd().split('Documents')[0],'Documents/BecaNLP/Utils'))

import NLPUtils as nlp

%load_ext autoreload
%autoreload 2

[nltk_data] Downloading package punkt to /home/lestien/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [70]:
from NLPUtils.datasets import get_dummy_corpus, imdb
from NLPUtils.feature_extraction import word_by_word_cooccurrence


# corpus = get_dummy_corpus('small')
corpus = imdb.get_train_dataframe()['comment']
X, vocab = word_by_word_cooccurrence(corpus,right_n=4,left_n=4,window=None,tokenizer=nlp.preprocessing.tokenize_sentence,
                                    min_count=0,max_count=None,max_words=5000)
# X, vocab = word_by_word_cooccurrence(corpus,right_n=2,left_n=2,window=None,tokenizer=None)
X.toarray()

100%|██████████| 25000/25000 [05:13<00:00, 79.69it/s] 


array([[3.64991e+05, 9.25230e+04, 6.59090e+04, ..., 3.20000e+01,
        2.70000e+01, 1.50000e+01],
       [9.25230e+04, 3.58818e+05, 4.09960e+04, ..., 4.40000e+01,
        4.00000e+01, 1.90000e+01],
       [6.59090e+04, 4.09960e+04, 2.46943e+05, ..., 2.50000e+01,
        6.60000e+01, 5.80000e+01],
       ...,
       [3.20000e+01, 4.40000e+01, 2.50000e+01, ..., 8.70000e+01,
        0.00000e+00, 0.00000e+00],
       [2.70000e+01, 4.00000e+01, 6.60000e+01, ..., 0.00000e+00,
        8.70000e+01, 0.00000e+00],
       [1.50000e+01, 1.90000e+01, 5.80000e+01, ..., 0.00000e+00,
        0.00000e+00, 8.70000e+01]])

In [1]:
import matplotlib.pyplot as plt

plt.hist(X.toarray().reshape(-1),10)

NameError: name 'X' is not defined

In [64]:
from NLPUtils.datasets import get_dummy_corpus, imdb
from NLPUtils.feature_extraction import word_by_document_cooccurrence

#corpus = get_dummy_corpus('small')
corpus = imdb.get_train_dataframe()['comment']
print(corpus.head())
X, vocab = word_by_document_cooccurrence(corpus,tokenizer=nlp.preprocessing.tokenize_sentence)
#X, vocab = word_by_document_cooccurrence(corpus,tokenizer=None,min_count=0,max_count=None,max_words=None)
X.toarray()

100%|██████████| 3/3 [00:00<00:00, 495.64it/s]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]], dtype=int64)

In [3]:
from NLPUtils.datasets import get_dummy_corpus, imdb
from NLPUtils.feature_extraction import word_by_category_cooccurrence

corpus = get_dummy_corpus('small')
print(corpus)
X, vocab = word_by_category_cooccurrence(corpus, labels=[0,1,1],tokenizer=None)
print(vocab)
X.toarray()

[['hola', ',', 'esto', 'es', 'una', 'prueba'], ['esto', 'es', 'otra', 'prueba'], ['esta', 'es', 'Una', 'prueba', 'más']]
{'hola': 0, ',': 1, 'esto': 2, 'es': 3, 'una': 4, 'prueba': 5, 'otra': 6, 'esta': 7, 'Una': 8, 'más': 9}


array([[1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 2.],
       [1., 0.],
       [1., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [5]:
from NLPUtils.datasets import get_dummy_corpus, imdb
from NLPUtils.feature_extraction import word_by_document_cooccurrence

corpus = get_dummy_corpus('small')
print(corpus)

X, vocab = word_by_document_cooccurrence(corpus,tokenizer=None)
print(vocab)
X.toarray()

100%|██████████| 3/3 [00:00<00:00, 3215.67it/s]

[['hola', ',', 'esto', 'es', 'una', 'prueba'], ['esto', 'es', 'otra', 'prueba'], ['esta', 'es', 'Una', 'prueba', 'más']]
{'hola': 0, ',': 1, 'esto': 2, 'es': 3, 'una': 4, 'prueba': 5, 'otra': 6, 'esta': 7, 'Una': 8, 'más': 9}


array([[1, 0, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 0, 0],
       [1, 1, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
from NLPUtils.datasets import get_dummy_corpus

corpus = [' '.join(doc) for doc in get_dummy_corpus('small')]
print(corpus)

vec = CountVectorizer(vocabulary='hola , esto es una prueba esta Una otra más'.split(' ') + ['esto es'],
                      token_pattern=r'\b\w+\b',ngram_range=(1,3))
X = vec.fit_transform(corpus)
print(vec.vocabulary_)
X.toarray()

['hola , esto es una prueba', 'esto es otra prueba', 'esta es Una prueba más']
{'hola': 0, ',': 1, 'esto': 2, 'es': 3, 'una': 4, 'prueba': 5, 'esta': 6, 'Una': 7, 'otra': 8, 'más': 9, 'esto es': 10}


array([[1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0]])

In [55]:
from NLPUtils.datasets import get_dummy_corpus, imdb
from NLPUtils.feature_extraction import word_by_word_cooccurrence

corpus = get_dummy_corpus('small')
print(corpus)

X, vocab = word_by_word_cooccurrence(corpus,tokenizer=None,min_count=0,max_count=None,max_words=None)
print(vocab)
print(X.toarray().sum(axis=1))
X.toarray()

100%|██████████| 3/3 [00:00<00:00, 2621.99it/s]

[['hola', ',', 'esto', 'es', 'una', 'prueba'], ['esto', 'es', 'otra', 'prueba'], ['esta', 'es', 'Una', 'prueba', 'más']]
{'hola': 0, ',': 1, 'esto': 2, 'es': 3, 'una': 4, 'prueba': 5, 'otra': 6, 'esta': 7, 'Una': 8, 'más': 9}
[10. 13.  8.  3.  5.  3.  4.  4.  4.  3.]


array([[3., 3., 0., 1., 1., 0., 1., 1., 0., 0.],
       [3., 3., 2., 0., 1., 1., 1., 1., 1., 0.],
       [0., 2., 2., 0., 0., 0., 1., 1., 1., 1.],
       [1., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 1.]])

# word2vec

In [2]:
from NLPUtils.feature_extraction import Word2VecTrainer
from NLPUtils.datasets import get_dummy_corpus

corpus = get_dummy_corpus('small')

trainer = Word2VecTrainer(corpus, left_n=2, right_n=2, tokenizer=None, min_count=0., max_count=None, max_words=None, algorithm='SkipGram', embeddings_dim=100, device='cpu')
